strategies:
- input_format: 'original text:

    {{text}}

    vocabularies:

    {{memory_vocab}}

    '
  model: openai/gpt-4o-mini
  output_name: correction
  prompt_name: correct_cn_audio_transcription
