strategies:
- input_format: '{{text}}'
  model: openai/gpt-4o-mini
  output_name: translation
  prompt_name: translate_cn
- input_format: 'original text:

    {{text}}

    translation:

    {{translation}}

    '
  model: openai/gpt-4o-mini
  output_name: reflection
  prompt_name: comment_cn_trans
- input_format: 'original text:

    {{text}}

    translation:

    {{translation}}

    comments:

    {{reflection}}

    '
  model: openai/gpt-4o-mini
  output_name: improvement
  prompt_name: improved_trans_cn
